server:
  port: 8082
spring:
  application:
    name: test
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    locations: /db/{vendor}/common, /db/{vendor}/test
